### PR TITLE
Merging 1_0_x with master

### PR DESCRIPTION
**Pull request by vijay-murali**

### CODE REVIEW

**Comment by vijay-murali** [comment]
@rmbarnett-rice, what is the purpose of the refactoring in commit e51c025? We do not expect to have any other kind of AST generation or synthesizer in Bayou. I suggest to discuss such refactoring before making the change, as it causes a whole lot of conflicts.

**Comment by rmbarnett-rice** [comment]
@vijay-murali Swarat mentioned that our industrial partner will attempt to remove the Python portion of the code in favor of using Java bindings for interfacing with Tensor Flow.  Prior to the commit you mention this would not have been possible without violating Open Close Principle. I solved this problem by introducing a layer of abstraction via Template Pattern. However, this required using loosely coupled components.  So this was a downstream change motivated originally by sidestepping the OCP issue.

**Comment by vijay-murali** [comment]
But why refactor EvidenceExtractor and Synthesizer for that? They are in Java anyway, and their interface is unaffected by which Tensorflow API is used.

**Comment by rmbarnett-rice** [comment]
Because of their use in Template Pattern here:

https://github.com/capergroup/bayou/blob/24a905c76699a95e00b2e896d32ce34d6afe70e1/src/main/java/edu/rice/cs/caper/bayou/application/api_synthesis_server/ExtractEvidenceGenAstsSynthesizeTemplate.java#L39

**Comment by vijay-murali** [comment]
I don't understand. Why would this piece of code not work if EvidenceExtractor and Synthesizer were just a class and not an interface?

**Comment by rmbarnett-rice** [comment]
It's not that the code wouldn't work, it is just that I saw template pattern as a way to solve the issue related to abstracting away how ast generation was performed to avoid a OCP violation. As side effect, template pattern also asked of me to introduce the abstractions related to how the extraction and synthesis were performed. As a proponent of loosely coupled components across namespace boundaries anyway, this did not appear onerous to me so I accepted the obligation.  I was unaware this would cause merge headaches.  If I had known, I probably would have introduced interfaces with a different name instead. e.g. IEvidecneExtractor or similar.  Sorry for the trouble.

**Comment by swaratchaudhuri** [comment]
I can see some eventual benefits in this change, in case we want to
synthesize for languages other than Java (for example Javascript). However,
I do think that we should be careful with refactorings...

-Swarat

**Comment by vijay-murali** [comment]
Aborting this pull request. Follow #45.

**Pull request closed without merging**
